spring:
  application:
    name: lovable-clone
    description: this is a app


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 856771506358-eha2vpkhe3jttrnv43mcpu6u5k0ihi0j.apps.googleusercontent.com
            client-secret: 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


  datasource:
    url: jdbc:postgresql://localhost:5432/lovable   # usually 5432, see note below
    username: postgres                              # usually 'postgres'
    password: v1a2r3s4h5a6
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


    ai:
      ollama: llama3.1:8b
      temperature: 0.7

jwt:
  secret-key: this_is_a_very_long_and_secure_jwt_secret_key_256_bits_minimum

razorpay:
  razorpay.key_id: rzp_test_RNQFCAGXB2IAK9
  razorpay.key_secret: TCMtYMcXjaiFJ8P4TzZ57Aca



logging:
  level:
    root: INFO
    org.springframework.web: WARN
    org.springframework.boot.autoconfigure: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.ai:
      chat.client: DEBUG
    com.lovable: DEBUG


  file:
    name: logs/application.log

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
